### PR TITLE
Add TYPO3 8.7 LTS compatibility and composer.json

### PR DESCRIPTION
**Pull request by tbal**
Also pushes version to 1.1.0 (-> minor update because of typo3 8.6 to 8.7 compatibility).

### CODE REVIEW

**Comment by codesource** [comment]
Thanks for the pull request.

**Comment by codesource** [comment]
Soon as https://extensions.typo3.org/ is available I will upload this new version to TER.

**Comment by tbal** [comment]
Great, thanks! Can you please leave a note here, if you uploaded the new version. Then i can use the official TER release again in my project, instead of my fork :)

**Comment by codesource** [comment]
The new version is uploaded on TER. 
Thanks again for your contribution.

**Pull request merged**
